Repository primitiv/primitiv, pull requests merged in 2018-03, with the labels that each got.

#168 Fix CMake script.
  primitiv/CMakeLists.txt
Labels: minor bug

#167 Graph/Operator changes to return multiple Nodes.
  examples/encdec/encdec.cc
  examples/encdec/encdec_attention.cc
  primitiv/graph.cc
  primitiv/graph.h
  primitiv/node_funcs.cc
  primitiv/operator.h
  primitiv/operator_impl.cc
  primitiv/operator_impl.h
  test/graph_test.cc
  test/operator_impl_test.cc
Labels: enhancement

#169 Use distribution's Eigen on Travis CI
  .travis/fedora.sh
  .travis/ubuntu.sh
Labels: refactoring

#170 Add split function
  examples/encdec/lstm.h
  examples/ptb/ptb_rnnlm_lstm.cc
  examples/ptb/ptb_rnnlm_sru.cc
  primitiv/basic_functions.h
  primitiv/node_funcs.cc
  primitiv/operator_impl.cc
  primitiv/operator_impl.h
  primitiv/tensor_funcs.cc
  test/graph_test.cc
  test/operator_impl_test.cc
  test/tensor_forward_test.cc
Labels: enhancement

#143 Use CLBlast instead of clBLAS
  .travis/debian.sh
  .travis/fedora.sh
  .travis/ubuntu.sh
  CMakeLists.txt
  cmake/FindCLBlast.cmake
  docs/source/installation.rst
  primitiv/CMakeLists.txt
  primitiv/opencl_device.cc
Labels: enhancement

#171 Add functions and fix minor issues for C APIs.
  primitiv/c/functions.cc
  primitiv/c/functions.h
  primitiv/c/graph.cc
  primitiv/c/graph.h
  primitiv/c/internal.h
  primitiv/c/optimizer.cc
  primitiv/c/shape.cc
  primitiv/c/shape.h
  primitiv/c/tensor.cc
  primitiv/c/tensor.h
  test/CMakeLists.txt
  test/c/graph_test.cc
  test/c/node_test.cc
  test/c/shape_test.cc
Labels: enhancement

#172 Add CLBlast include directory
  CMakeLists.txt
Labels: minor bug

#173 Add PRIMITIV_USE_CUDNN option.
  CMakeLists.txt
  docs/source/reference/build_options.rst
  primitiv/config.h.in
  primitiv/device_ops/cuda/conv2d.cu
  primitiv/device_ops/cuda/max_pool2d.cu
  primitiv/device_ops/cuda16/conv2d.cu
  primitiv/device_ops/cuda16/max_pool2d.cu
  primitiv/internal/cuda_utils.h
Labels: enhancement

#178 Fix a minor issue for C APIs.
  primitiv/c/shape.cc
  test/c/shape_test.cc
Labels: minor bug
