Repository primitiv/primitiv, pull requests merged in 2018-04, with the labels that each got.

#180 Disable x86 test
  .travis.yml
Labels: major bug

#186 Use a released tarball of Eigen on Travis CI
  .travis/debian.sh
Labels: minor bug

#184 Use nextafter for dealing with excess precision
  primitiv/random.h
Labels: major bug

#182 Add max() and min() functions
  primitiv/basic_functions.h
  primitiv/c/functions.cc
  primitiv/c/functions.h
  primitiv/cuda16_device.h
  primitiv/cuda_device.h
  primitiv/device.cc
  primitiv/device.h
  primitiv/device_ops/cuda/argmax.cu
  primitiv/device_ops/cuda/argmin.cu
  primitiv/device_ops/cuda/max.cu
  primitiv/device_ops/cuda/min.cu
  primitiv/device_ops/cuda16/argmax.cu
  primitiv/device_ops/cuda16/argmin.cu
  primitiv/device_ops/cuda16/max.cu
  primitiv/device_ops/cuda16/min.cu
  primitiv/device_ops/eigen/max.cc
  primitiv/device_ops/eigen/min.cc
  primitiv/device_ops/naive/max.cc
  primitiv/device_ops/naive/min.cc
  primitiv/eigen_device.h
  primitiv/naive_device.h
  primitiv/node_funcs.cc
  primitiv/opencl_device.cc
  primitiv/opencl_device.h
  primitiv/opencl_device_kernel.cl
  primitiv/operator_impl.cc
  primitiv/operator_impl.h
  primitiv/tensor_funcs.cc
  test/tensor_backward_test.cc
  test/tensor_forward_test.cc
  test/tensor_test.cc
Labels: enhancement

#179 Add batch manipulation functions.
  primitiv/basic_functions.h
  primitiv/c/functions.cc
  primitiv/c/functions.h
  primitiv/cuda16_device.h
  primitiv/cuda_device.h
  primitiv/device.cc
  primitiv/device.h
  primitiv/device_ops/cuda/batch_concat.cu
  primitiv/device_ops/cuda/batch_pick.cu
  primitiv/device_ops/cuda/batch_slice.cu
  primitiv/device_ops/cuda16/batch_concat.cu
  primitiv/device_ops/cuda16/batch_pick.cu
  primitiv/device_ops/cuda16/batch_slice.cu
  primitiv/device_ops/eigen/batch_concat.cc
  primitiv/device_ops/eigen/batch_pick.cc
  primitiv/device_ops/eigen/batch_slice.cc
  primitiv/device_ops/naive/batch_concat.cc
  primitiv/device_ops/naive/batch_pick.cc
  primitiv/device_ops/naive/batch_slice.cc
  primitiv/eigen_device.h
  primitiv/naive_device.h
  primitiv/node_funcs.cc
  primitiv/opencl_device.cc
  primitiv/opencl_device.h
  primitiv/opencl_device_kernel.cl
  primitiv/operator_impl.cc
  primitiv/operator_impl.h
  primitiv/shape_ops.cc
  primitiv/shape_ops.h
  primitiv/tensor_funcs.cc
  test/operator_impl_test.cc
  test/shape_ops_test.cc
  test/tensor_backward_test.cc
  test/tensor_forward_test.cc
Labels: enhancement
